# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI_devPhCeJn.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFormLayout, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1709, 868)
        font = QFont()
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 90, 301, 361))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_3 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.verticalLayout.addWidget(self.pushButton_3)

        self.pushButton_2 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.verticalLayout.addWidget(self.pushButton_2)

        self.pushButton_classification = QPushButton(self.verticalLayoutWidget)
        self.pushButton_classification.setObjectName(u"pushButton_classification")

        self.verticalLayout.addWidget(self.pushButton_classification)

        self.pushButton_regression = QPushButton(self.verticalLayoutWidget)
        self.pushButton_regression.setObjectName(u"pushButton_regression")

        self.verticalLayout.addWidget(self.pushButton_regression)

        self.pushButton_A2O = QPushButton(self.verticalLayoutWidget)
        self.pushButton_A2O.setObjectName(u"pushButton_A2O")

        self.verticalLayout.addWidget(self.pushButton_A2O)

        self.pushButton_Bardenpho = QPushButton(self.verticalLayoutWidget)
        self.pushButton_Bardenpho.setObjectName(u"pushButton_Bardenpho")

        self.verticalLayout.addWidget(self.pushButton_Bardenpho)

        self.pushButton_Johannesburg = QPushButton(self.verticalLayoutWidget)
        self.pushButton_Johannesburg.setObjectName(u"pushButton_Johannesburg")

        self.verticalLayout.addWidget(self.pushButton_Johannesburg)

        self.pushButton_UCT = QPushButton(self.verticalLayoutWidget)
        self.pushButton_UCT.setObjectName(u"pushButton_UCT")

        self.verticalLayout.addWidget(self.pushButton_UCT)

        self.pushButton = QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setAutoDefault(False)

        self.verticalLayout.addWidget(self.pushButton)

        self.pushButton_NNCL = QPushButton(self.verticalLayoutWidget)
        self.pushButton_NNCL.setObjectName(u"pushButton_NNCL")

        self.verticalLayout.addWidget(self.pushButton_NNCL)

        self.pushButton_GPC_2 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_GPC_2.setObjectName(u"pushButton_GPC_2")

        self.verticalLayout.addWidget(self.pushButton_GPC_2)

        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(60, 10, 181, 41))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(True)
        self.pushButton_4.setFont(font1)
        self.pushButton_4.setAutoFillBackground(False)
        self.verticalLayoutWidget_3 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(400, 0, 321, 91))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName(u"label_2")
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(False)
        self.label_2.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_2)

        self.label_3 = QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_3)

        self.label_4 = QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_4)

        self.verticalLayoutWidget_4 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(10, 450, 301, 116))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pushBoutton_back_4 = QPushButton(self.verticalLayoutWidget_4)
        self.pushBoutton_back_4.setObjectName(u"pushBoutton_back_4")

        self.verticalLayout_4.addWidget(self.pushBoutton_back_4)

        self.pushButton_5 = QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_5.setObjectName(u"pushButton_5")

        self.verticalLayout_4.addWidget(self.pushButton_5)

        self.pushButton_Back2 = QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_Back2.setObjectName(u"pushButton_Back2")

        self.verticalLayout_4.addWidget(self.pushButton_Back2)

        self.pushButton_Back_3 = QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_Back_3.setObjectName(u"pushButton_Back_3")

        self.verticalLayout_4.addWidget(self.pushButton_Back_3)

        self.formLayoutWidget = QWidget(self.centralwidget)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(330, 100, 461, 712))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setFormAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setContentsMargins(0, 0, 1, 0)
        self.radioButton_four = QRadioButton(self.formLayoutWidget)
        self.radioButton_four.setObjectName(u"radioButton_four")

        self.formLayout.setWidget(17, QFormLayout.LabelRole, self.radioButton_four)

        self.radioButton_Poly = QRadioButton(self.formLayoutWidget)
        self.radioButton_Poly.setObjectName(u"radioButton_Poly")

        self.formLayout.setWidget(16, QFormLayout.LabelRole, self.radioButton_Poly)

        self.radioButton_SoftPlus = QRadioButton(self.formLayoutWidget)
        self.radioButton_SoftPlus.setObjectName(u"radioButton_SoftPlus")
        self.radioButton_SoftPlus.setEnabled(True)

        self.formLayout.setWidget(15, QFormLayout.LabelRole, self.radioButton_SoftPlus)

        self.radioButton_RBF = QRadioButton(self.formLayoutWidget)
        self.radioButton_RBF.setObjectName(u"radioButton_RBF")

        self.formLayout.setWidget(14, QFormLayout.LabelRole, self.radioButton_RBF)

        self.radioButton_ESS = QRadioButton(self.formLayoutWidget)
        self.radioButton_ESS.setObjectName(u"radioButton_ESS")

        self.formLayout.setWidget(13, QFormLayout.LabelRole, self.radioButton_ESS)

        self.radioButton_Linear = QRadioButton(self.formLayoutWidget)
        self.radioButton_Linear.setObjectName(u"radioButton_Linear")

        self.formLayout.setWidget(12, QFormLayout.LabelRole, self.radioButton_Linear)

        self.radioButton_Matern = QRadioButton(self.formLayoutWidget)
        self.radioButton_Matern.setObjectName(u"radioButton_Matern")

        self.formLayout.setWidget(9, QFormLayout.LabelRole, self.radioButton_Matern)

        self.radioButton_Three = QRadioButton(self.formLayoutWidget)
        self.radioButton_Three.setObjectName(u"radioButton_Three")

        self.formLayout.setWidget(8, QFormLayout.LabelRole, self.radioButton_Three)

        self.radioButton_Leaky_ReLu = QRadioButton(self.formLayoutWidget)
        self.radioButton_Leaky_ReLu.setObjectName(u"radioButton_Leaky_ReLu")
        self.radioButton_Leaky_ReLu.setEnabled(True)

        self.formLayout.setWidget(7, QFormLayout.LabelRole, self.radioButton_Leaky_ReLu)

        self.radioButton_Swish = QRadioButton(self.formLayoutWidget)
        self.radioButton_Swish.setObjectName(u"radioButton_Swish")
        self.radioButton_Swish.setEnabled(True)

        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.radioButton_Swish)

        self.radioButton_ReLu = QRadioButton(self.formLayoutWidget)
        self.radioButton_ReLu.setObjectName(u"radioButton_ReLu")
        self.radioButton_ReLu.setEnabled(True)

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.radioButton_ReLu)

        self.radioButton_two = QRadioButton(self.formLayoutWidget)
        self.radioButton_two.setObjectName(u"radioButton_two")

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.radioButton_two)

        self.radioButton_RQ = QRadioButton(self.formLayoutWidget)
        self.radioButton_RQ.setObjectName(u"radioButton_RQ")

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.radioButton_RQ)

        self.radioButton_Serf = QRadioButton(self.formLayoutWidget)
        self.radioButton_Serf.setObjectName(u"radioButton_Serf")
        self.radioButton_Serf.setEnabled(True)

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.radioButton_Serf)

        self.pushButton_Serf = QPushButton(self.formLayoutWidget)
        self.pushButton_Serf.setObjectName(u"pushButton_Serf")

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.pushButton_Serf)

        self.pushButton_RQ = QPushButton(self.formLayoutWidget)
        self.pushButton_RQ.setObjectName(u"pushButton_RQ")

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.pushButton_RQ)

        self.pushButton_two = QPushButton(self.formLayoutWidget)
        self.pushButton_two.setObjectName(u"pushButton_two")

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.pushButton_two)

        self.pushButton_ReLu = QPushButton(self.formLayoutWidget)
        self.pushButton_ReLu.setObjectName(u"pushButton_ReLu")

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.pushButton_ReLu)

        self.pushButton_Swish = QPushButton(self.formLayoutWidget)
        self.pushButton_Swish.setObjectName(u"pushButton_Swish")

        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.pushButton_Swish)

        self.pushButton_Leaky_ReLu = QPushButton(self.formLayoutWidget)
        self.pushButton_Leaky_ReLu.setObjectName(u"pushButton_Leaky_ReLu")

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.pushButton_Leaky_ReLu)

        self.pushButton_Three = QPushButton(self.formLayoutWidget)
        self.pushButton_Three.setObjectName(u"pushButton_Three")

        self.formLayout.setWidget(8, QFormLayout.FieldRole, self.pushButton_Three)

        self.pushButton_Matern = QPushButton(self.formLayoutWidget)
        self.pushButton_Matern.setObjectName(u"pushButton_Matern")

        self.formLayout.setWidget(9, QFormLayout.FieldRole, self.pushButton_Matern)

        self.pushButton_Linear = QPushButton(self.formLayoutWidget)
        self.pushButton_Linear.setObjectName(u"pushButton_Linear")

        self.formLayout.setWidget(12, QFormLayout.FieldRole, self.pushButton_Linear)

        self.pushButton_ESS = QPushButton(self.formLayoutWidget)
        self.pushButton_ESS.setObjectName(u"pushButton_ESS")

        self.formLayout.setWidget(13, QFormLayout.FieldRole, self.pushButton_ESS)

        self.pushButton_RBF = QPushButton(self.formLayoutWidget)
        self.pushButton_RBF.setObjectName(u"pushButton_RBF")

        self.formLayout.setWidget(14, QFormLayout.FieldRole, self.pushButton_RBF)

        self.pushButton_Softplus = QPushButton(self.formLayoutWidget)
        self.pushButton_Softplus.setObjectName(u"pushButton_Softplus")

        self.formLayout.setWidget(15, QFormLayout.FieldRole, self.pushButton_Softplus)

        self.pushButton_Poly = QPushButton(self.formLayoutWidget)
        self.pushButton_Poly.setObjectName(u"pushButton_Poly")

        self.formLayout.setWidget(16, QFormLayout.FieldRole, self.pushButton_Poly)

        self.pushButton_four = QPushButton(self.formLayoutWidget)
        self.pushButton_four.setObjectName(u"pushButton_four")

        self.formLayout.setWidget(17, QFormLayout.FieldRole, self.pushButton_four)

        self.label_loss = QLabel(self.formLayoutWidget)
        self.label_loss.setObjectName(u"label_loss")
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(12)
        font3.setBold(True)
        self.label_loss.setFont(font3)

        self.formLayout.setWidget(23, QFormLayout.LabelRole, self.label_loss)

        self.radioButton_Sum_RBF = QRadioButton(self.formLayoutWidget)
        self.radioButton_Sum_RBF.setObjectName(u"radioButton_Sum_RBF")

        self.formLayout.setWidget(11, QFormLayout.LabelRole, self.radioButton_Sum_RBF)

        self.pushButton_Sum_RBF = QPushButton(self.formLayoutWidget)
        self.pushButton_Sum_RBF.setObjectName(u"pushButton_Sum_RBF")

        self.formLayout.setWidget(11, QFormLayout.FieldRole, self.pushButton_Sum_RBF)

        self.radioButton_Sum_RQ = QRadioButton(self.formLayoutWidget)
        self.radioButton_Sum_RQ.setObjectName(u"radioButton_Sum_RQ")

        self.formLayout.setWidget(10, QFormLayout.LabelRole, self.radioButton_Sum_RQ)

        self.pushButton_Sum_RQ = QPushButton(self.formLayoutWidget)
        self.pushButton_Sum_RQ.setObjectName(u"pushButton_Sum_RQ")

        self.formLayout.setWidget(10, QFormLayout.FieldRole, self.pushButton_Sum_RQ)

        self.pushButton_GPC = QPushButton(self.formLayoutWidget)
        self.pushButton_GPC.setObjectName(u"pushButton_GPC")

        self.formLayout.setWidget(23, QFormLayout.FieldRole, self.pushButton_GPC)

        self.radioButton_Serf_cl = QRadioButton(self.formLayoutWidget)
        self.radioButton_Serf_cl.setObjectName(u"radioButton_Serf_cl")

        self.formLayout.setWidget(18, QFormLayout.LabelRole, self.radioButton_Serf_cl)

        self.radioButton_Swish_cl = QRadioButton(self.formLayoutWidget)
        self.radioButton_Swish_cl.setObjectName(u"radioButton_Swish_cl")

        self.formLayout.setWidget(19, QFormLayout.LabelRole, self.radioButton_Swish_cl)

        self.radioButton_ReLu_cl = QRadioButton(self.formLayoutWidget)
        self.radioButton_ReLu_cl.setObjectName(u"radioButton_ReLu_cl")

        self.formLayout.setWidget(20, QFormLayout.LabelRole, self.radioButton_ReLu_cl)

        self.radioButton_Leaky_ReLu_cl = QRadioButton(self.formLayoutWidget)
        self.radioButton_Leaky_ReLu_cl.setObjectName(u"radioButton_Leaky_ReLu_cl")

        self.formLayout.setWidget(21, QFormLayout.LabelRole, self.radioButton_Leaky_ReLu_cl)

        self.pushButton_Serf_cl = QPushButton(self.formLayoutWidget)
        self.pushButton_Serf_cl.setObjectName(u"pushButton_Serf_cl")

        self.formLayout.setWidget(18, QFormLayout.FieldRole, self.pushButton_Serf_cl)

        self.pushButton_Swish_cl = QPushButton(self.formLayoutWidget)
        self.pushButton_Swish_cl.setObjectName(u"pushButton_Swish_cl")

        self.formLayout.setWidget(19, QFormLayout.FieldRole, self.pushButton_Swish_cl)

        self.pushButton_Relu_cl = QPushButton(self.formLayoutWidget)
        self.pushButton_Relu_cl.setObjectName(u"pushButton_Relu_cl")

        self.formLayout.setWidget(20, QFormLayout.FieldRole, self.pushButton_Relu_cl)

        self.pushButton_Leaky_ReLu_cl = QPushButton(self.formLayoutWidget)
        self.pushButton_Leaky_ReLu_cl.setObjectName(u"pushButton_Leaky_ReLu_cl")

        self.formLayout.setWidget(21, QFormLayout.FieldRole, self.pushButton_Leaky_ReLu_cl)

        self.radioButton_Soft_Plus_cl = QRadioButton(self.formLayoutWidget)
        self.radioButton_Soft_Plus_cl.setObjectName(u"radioButton_Soft_Plus_cl")

        self.formLayout.setWidget(22, QFormLayout.LabelRole, self.radioButton_Soft_Plus_cl)

        self.pushButton_Soft_Plus_cl = QPushButton(self.formLayoutWidget)
        self.pushButton_Soft_Plus_cl.setObjectName(u"pushButton_Soft_Plus_cl")

        self.formLayout.setWidget(22, QFormLayout.FieldRole, self.pushButton_Soft_Plus_cl)

        self.radioButton_Sigmoid = QRadioButton(self.formLayoutWidget)
        self.radioButton_Sigmoid.setObjectName(u"radioButton_Sigmoid")

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.radioButton_Sigmoid)

        self.pushButton_Sigmoid = QPushButton(self.formLayoutWidget)
        self.pushButton_Sigmoid.setObjectName(u"pushButton_Sigmoid")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.pushButton_Sigmoid)

        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(810, 110, 361, 31))
        self.lineEdit.setClearButtonEnabled(False)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(810, 60, 361, 51))
        self.label_5.setFont(font2)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_predict = QLabel(self.centralwidget)
        self.label_predict.setObjectName(u"label_predict")
        self.label_predict.setGeometry(QRect(10, 540, 861, 301))
        font4 = QFont()
        font4.setFamilies([u"Arial Black"])
        font4.setPointSize(10)
        font4.setBold(False)
        self.label_predict.setFont(font4)
        self.verticalLayoutWidget_5 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(10, 40, 323, 80))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget_5)
        self.label.setObjectName(u"label")
        self.label.setFont(font2)

        self.verticalLayout_5.addWidget(self.label)

        self.label_BNR = QLabel(self.verticalLayoutWidget_5)
        self.label_BNR.setObjectName(u"label_BNR")
        self.label_BNR.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_BNR)

        self.label_6 = QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_6)

        self.pushButton_show_results = QPushButton(self.centralwidget)
        self.pushButton_show_results.setObjectName(u"pushButton_show_results")
        self.pushButton_show_results.setGeometry(QRect(860, 150, 271, 31))
        self.verticalLayoutWidget_2 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(810, 190, 361, 621))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMaximumSize(QSize(16777215, 25))
        self.label_7.setFont(font2)
        self.label_7.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_7)

        self.label_num_indiv = QLabel(self.verticalLayoutWidget_2)
        self.label_num_indiv.setObjectName(u"label_num_indiv")
        self.label_num_indiv.setMaximumSize(QSize(16777215, 25))
        self.label_num_indiv.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_num_indiv)

        self.lineEdit_num_indiv = QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_num_indiv.setObjectName(u"lineEdit_num_indiv")

        self.verticalLayout_2.addWidget(self.lineEdit_num_indiv)

        self.label_num_gen = QLabel(self.verticalLayoutWidget_2)
        self.label_num_gen.setObjectName(u"label_num_gen")
        self.label_num_gen.setMaximumSize(QSize(16777215, 25))
        self.label_num_gen.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_num_gen)

        self.lineEdit_num_gen = QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_num_gen.setObjectName(u"lineEdit_num_gen")

        self.verticalLayout_2.addWidget(self.lineEdit_num_gen)

        self.pushButton_opti_Sigmoid = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_Sigmoid.setObjectName(u"pushButton_opti_Sigmoid")

        self.verticalLayout_2.addWidget(self.pushButton_opti_Sigmoid)

        self.pushButton_opti_Two = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_Two.setObjectName(u"pushButton_opti_Two")

        self.verticalLayout_2.addWidget(self.pushButton_opti_Two)

        self.pushButton_opti_ReLu = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_ReLu.setObjectName(u"pushButton_opti_ReLu")

        self.verticalLayout_2.addWidget(self.pushButton_opti_ReLu)

        self.pushButton_opti_Swish = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_Swish.setObjectName(u"pushButton_opti_Swish")

        self.verticalLayout_2.addWidget(self.pushButton_opti_Swish)

        self.pushButton_opti_Leaky_ReLu = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_Leaky_ReLu.setObjectName(u"pushButton_opti_Leaky_ReLu")

        self.verticalLayout_2.addWidget(self.pushButton_opti_Leaky_ReLu)

        self.pushButton_opti_Softplus = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_Softplus.setObjectName(u"pushButton_opti_Softplus")

        self.verticalLayout_2.addWidget(self.pushButton_opti_Softplus)

        self.pushButton_opti_Four = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_Four.setObjectName(u"pushButton_opti_Four")

        self.verticalLayout_2.addWidget(self.pushButton_opti_Four)

        self.pushButton_opti_Three = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_Three.setObjectName(u"pushButton_opti_Three")

        self.verticalLayout_2.addWidget(self.pushButton_opti_Three)

        self.pushButton_opti_Serf = QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_opti_Serf.setObjectName(u"pushButton_opti_Serf")

        self.verticalLayout_2.addWidget(self.pushButton_opti_Serf)

        self.label_results_opti = QLabel(self.centralwidget)
        self.label_results_opti.setObjectName(u"label_results_opti")
        self.label_results_opti.setGeometry(QRect(770, 770, 891, 51))
        self.label_results_opti.setMaximumSize(QSize(16777215, 100))
        self.label_results_opti.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_predict.raise_()
        self.verticalLayoutWidget.raise_()
        self.pushButton_4.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.formLayoutWidget.raise_()
        self.lineEdit.raise_()
        self.label_5.raise_()
        self.verticalLayoutWidget_5.raise_()
        self.pushButton_show_results.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.label_results_opti.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1709, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.pushButton, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.pushButton_2)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.pushButton_3.hide)
        self.pushButton.clicked.connect(self.radioButton_Serf.show)
        self.pushButton_4.clicked.connect(self.radioButton_Serf.hide)
        self.pushButton_4.clicked.connect(self.radioButton_ReLu.hide)
        self.pushButton_4.clicked.connect(self.radioButton_SoftPlus.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Leaky_ReLu.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Swish.hide)
        self.pushButton.clicked.connect(self.radioButton_ReLu.show)
        self.pushButton.clicked.connect(self.radioButton_SoftPlus.show)
        self.pushButton.clicked.connect(self.label.hide)
        self.pushButton.clicked.connect(self.radioButton_Leaky_ReLu.show)
        self.pushButton.clicked.connect(self.radioButton_Swish.show)
        self.pushButton.clicked.connect(self.pushButton_4.hide)
        self.pushButton_4.clicked.connect(self.label_2.hide)
        self.pushButton.clicked.connect(self.label_2.show)
        self.pushButton_4.clicked.connect(self.radioButton_ESS.hide)
        self.pushButton_4.clicked.connect(self.radioButton_RQ.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Poly.hide)
        self.pushButton_4.clicked.connect(self.radioButton_RBF.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Matern.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Linear.hide)
        self.pushButton_4.clicked.connect(self.label_3.hide)
        self.pushButton_3.clicked.connect(self.pushButton.hide)
        self.pushButton_3.clicked.connect(self.pushButton_2.hide)
        self.pushButton_3.clicked.connect(self.pushButton_4.hide)
        self.pushButton_3.clicked.connect(self.radioButton_ESS.show)
        self.pushButton_3.clicked.connect(self.radioButton_RQ.show)
        self.pushButton_3.clicked.connect(self.radioButton_Poly.show)
        self.pushButton_3.clicked.connect(self.radioButton_RBF.show)
        self.pushButton_3.clicked.connect(self.radioButton_Matern.show)
        self.pushButton_3.clicked.connect(self.radioButton_Linear.show)
        self.pushButton_3.clicked.connect(self.label_2.hide)
        self.pushButton_3.clicked.connect(self.label.hide)
        self.pushButton_3.clicked.connect(self.label_3.show)
        self.pushButton_2.clicked.connect(self.pushButton.hide)
        self.pushButton_2.clicked.connect(self.pushButton_3.hide)
        self.pushButton_2.clicked.connect(self.pushButton_4.hide)
        self.pushButton_4.clicked.connect(self.label_4.hide)
        self.pushButton_4.clicked.connect(self.radioButton_two.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Three.hide)
        self.pushButton_4.clicked.connect(self.radioButton_four.hide)
        self.pushButton_2.clicked.connect(self.label_4.show)
        self.pushButton_2.clicked.connect(self.radioButton_Three.show)
        self.pushButton_2.clicked.connect(self.radioButton_two.show)
        self.pushButton_2.clicked.connect(self.radioButton_four.show)
        self.pushButton_2.clicked.connect(self.label.hide)
        self.pushButton_5.clicked.connect(self.pushButton.show)
        self.pushButton_5.clicked.connect(self.pushButton_2.show)
        self.pushButton_5.clicked.connect(self.pushButton_3.show)
        self.pushButton_5.clicked.connect(self.radioButton_Serf.hide)
        self.pushButton_5.clicked.connect(self.radioButton_Matern.hide)
        self.pushButton_5.clicked.connect(self.radioButton_Linear.hide)
        self.pushButton_5.clicked.connect(self.radioButton_two.hide)
        self.pushButton_5.clicked.connect(self.radioButton_Three.hide)
        self.pushButton_5.clicked.connect(self.radioButton_four.hide)
        self.pushButton_5.clicked.connect(self.radioButton_ReLu.hide)
        self.pushButton_5.clicked.connect(self.radioButton_SoftPlus.hide)
        self.pushButton_5.clicked.connect(self.radioButton_Leaky_ReLu.hide)
        self.pushButton_5.clicked.connect(self.radioButton_Swish.hide)
        self.pushButton_5.clicked.connect(self.radioButton_ESS.hide)
        self.pushButton_5.clicked.connect(self.radioButton_RQ.hide)
        self.pushButton_5.clicked.connect(self.radioButton_Poly.hide)
        self.pushButton_5.clicked.connect(self.radioButton_RBF.hide)
        self.pushButton_5.clicked.connect(self.label_2.hide)
        self.pushButton_5.clicked.connect(self.label_3.hide)
        self.pushButton_5.clicked.connect(self.label_4.hide)
        self.pushButton_5.clicked.connect(self.label.show)
        self.pushButton_4.clicked.connect(self.pushButton_ESS.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Leaky_ReLu.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Linear.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Matern.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Poly.hide)
        self.pushButton_4.clicked.connect(self.pushButton_RBF.hide)
        self.pushButton_4.clicked.connect(self.pushButton_RQ.hide)
        self.pushButton_4.clicked.connect(self.pushButton_ReLu.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Serf.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Softplus.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Swish.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Three.hide)
        self.pushButton_4.clicked.connect(self.pushButton_four.hide)
        self.pushButton_4.clicked.connect(self.pushButton_two.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Poly.hide)
        self.pushButton_5.clicked.connect(self.pushButton_two.hide)
        self.pushButton_5.clicked.connect(self.pushButton_four.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Three.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Swish.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Softplus.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Serf.hide)
        self.pushButton_5.clicked.connect(self.pushButton_ReLu.hide)
        self.pushButton_5.clicked.connect(self.pushButton_RQ.hide)
        self.pushButton_5.clicked.connect(self.pushButton_RBF.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Poly.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Matern.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Linear.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Leaky_ReLu.hide)
        self.pushButton_5.clicked.connect(self.pushButton_ESS.hide)
        self.radioButton_Matern.clicked.connect(self.pushButton_Matern.show)
        self.radioButton_ESS.clicked.connect(self.pushButton_ESS.show)
        self.radioButton_ESS.clicked.connect(self.pushButton_RBF.hide)
        self.radioButton_ESS.clicked.connect(self.pushButton_RQ.hide)
        self.radioButton_ESS.clicked.connect(self.pushButton_Poly.hide)
        self.radioButton_ESS.clicked.connect(self.pushButton_Linear.hide)
        self.radioButton_ESS.clicked.connect(self.pushButton_Matern.hide)
        self.radioButton_Linear.clicked.connect(self.pushButton_Linear.show)
        self.radioButton_Linear.clicked.connect(self.pushButton_ESS.hide)
        self.radioButton_Linear.clicked.connect(self.pushButton_Matern.hide)
        self.radioButton_Linear.clicked.connect(self.pushButton_Poly.hide)
        self.radioButton_Linear.clicked.connect(self.pushButton_RBF.hide)
        self.radioButton_Linear.clicked.connect(self.pushButton_RQ.hide)
        self.radioButton_Matern.clicked.connect(self.pushButton_ESS.hide)
        self.radioButton_Matern.clicked.connect(self.pushButton_Linear.hide)
        self.radioButton_Matern.clicked.connect(self.pushButton_Poly.hide)
        self.pushButton.clicked.connect(self.pushButton_2.hide)
        self.radioButton_Matern.clicked.connect(self.pushButton_RBF.hide)
        self.radioButton_Matern.clicked.connect(self.pushButton_RQ.hide)
        self.radioButton_Poly.clicked.connect(self.pushButton_ESS.hide)
        self.radioButton_Poly.clicked.connect(self.pushButton_Linear.hide)
        self.radioButton_Poly.clicked.connect(self.pushButton_Matern.hide)
        self.radioButton_Poly.clicked.connect(self.pushButton_Poly.show)
        self.radioButton_Poly.clicked.connect(self.pushButton_RBF.hide)
        self.radioButton_Poly.clicked.connect(self.pushButton_RQ.hide)
        self.radioButton_RBF.clicked.connect(self.pushButton_ESS.hide)
        self.radioButton_RBF.clicked.connect(self.pushButton_Linear.hide)
        self.radioButton_RBF.clicked.connect(self.pushButton_Matern.hide)
        self.radioButton_RBF.clicked.connect(self.pushButton_Poly.hide)
        self.radioButton_RBF.clicked.connect(self.pushButton_RBF.show)
        self.radioButton_RBF.clicked.connect(self.pushButton_RQ.hide)
        self.radioButton_RQ.clicked.connect(self.pushButton_ESS.hide)
        self.radioButton_RQ.clicked.connect(self.pushButton_Linear.hide)
        self.radioButton_RQ.clicked.connect(self.pushButton_Matern.hide)
        self.radioButton_RQ.clicked.connect(self.pushButton_Poly.hide)
        self.radioButton_RQ.clicked.connect(self.pushButton_RBF.hide)
        self.radioButton_RQ.clicked.connect(self.pushButton_RQ.show)
        self.pushButton_4.clicked.connect(self.pushButton_4.hide)
        self.radioButton_two.clicked.connect(self.pushButton_two.show)
        self.radioButton_two.clicked.connect(self.pushButton_Three.hide)
        self.radioButton_two.clicked.connect(self.pushButton_four.hide)
        self.radioButton_Three.clicked.connect(self.pushButton_Three.show)
        self.radioButton_Three.clicked.connect(self.pushButton_two.hide)
        self.radioButton_Three.clicked.connect(self.pushButton_four.hide)
        self.radioButton_four.clicked.connect(self.pushButton_four.show)
        self.radioButton_four.clicked.connect(self.pushButton_Three.hide)
        self.radioButton_four.clicked.connect(self.pushButton_two.hide)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_Leaky_ReLu.show)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_ReLu.hide)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_Serf.hide)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_Softplus.hide)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_Swish.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_Leaky_ReLu.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_ReLu.show)
        self.radioButton_ReLu.clicked.connect(self.pushButton_Serf.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_Softplus.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_Swish.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_Leaky_ReLu.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_ReLu.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_Serf.show)
        self.radioButton_Serf.clicked.connect(self.pushButton_Softplus.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_Swish.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_Leaky_ReLu.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_ReLu.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_Serf.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_Softplus.show)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_Swish.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_Leaky_ReLu.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_ReLu.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_Serf.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_Softplus.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_Swish.show)
        self.pushButton_5.clicked.connect(self.label_loss.hide)
        self.pushButton_ESS.clicked.connect(self.label_loss.show)
        self.pushButton_Leaky_ReLu.clicked.connect(self.label_loss.show)
        self.pushButton_Linear.clicked.connect(self.label_loss.show)
        self.pushButton_Matern.clicked.connect(self.label_loss.show)
        self.pushButton_Poly.clicked.connect(self.label_loss.show)
        self.pushButton_RBF.clicked.connect(self.label_loss.show)
        self.pushButton_RQ.clicked.connect(self.label_loss.show)
        self.pushButton_ReLu.clicked.connect(self.label_loss.show)
        self.pushButton_Serf.clicked.connect(self.label_loss.show)
        self.pushButton_Softplus.clicked.connect(self.label_loss.show)
        self.pushButton_Swish.clicked.connect(self.label_loss.show)
        self.pushButton_Three.clicked.connect(self.label_loss.show)
        self.pushButton_four.clicked.connect(self.label_loss.show)
        self.pushButton_two.clicked.connect(self.label_loss.show)
        self.pushButton_4.clicked.connect(self.label_5.hide)
        self.pushButton_3.clicked.connect(self.label_5.show)
        self.pushButton_2.clicked.connect(self.label_5.show)
        self.pushButton.clicked.connect(self.label_5.show)
        self.pushButton_5.clicked.connect(self.label_5.hide)
        self.pushButton_3.clicked.connect(self.lineEdit.show)
        self.pushButton_4.clicked.connect(self.lineEdit.hide)
        self.pushButton_2.clicked.connect(self.lineEdit.show)
        self.pushButton.clicked.connect(self.lineEdit.show)
        self.pushButton_5.clicked.connect(self.lineEdit.hide)
        self.pushButton_5.clicked.connect(self.label_predict.hide)
        self.pushButton.clicked.connect(self.label_predict.show)
        self.pushButton_2.clicked.connect(self.label_predict.show)
        self.pushButton_3.clicked.connect(self.label_predict.show)
        self.pushButton_5.clicked.connect(self.label_predict.clear)
        self.pushButton_4.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Sum_RBF.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Sum_RQ.hide)
        self.pushButton_3.clicked.connect(self.radioButton_Sum_RBF.show)
        self.pushButton_3.clicked.connect(self.radioButton_Sum_RQ.show)
        self.pushButton_5.clicked.connect(self.radioButton_Sum_RBF.hide)
        self.pushButton_5.clicked.connect(self.radioButton_Sum_RQ.hide)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_ESS.hide)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_Linear.hide)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_Matern.hide)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_Poly.hide)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_RBF.hide)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_RQ.hide)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_Sum_RBF.show)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.radioButton_ESS.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.radioButton_ESS.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.radioButton_Linear.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.radioButton_Linear.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.radioButton_Matern.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.radioButton_Matern.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.radioButton_Poly.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.radioButton_Poly.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.radioButton_RBF.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.radioButton_RBF.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.radioButton_RQ.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.radioButton_RQ.clicked.connect(self.pushButton_Sum_RQ.hide)
        self.radioButton_Sum_RQ.clicked.connect(self.pushButton_ESS.hide)
        self.radioButton_Sum_RQ.clicked.connect(self.pushButton_Linear.hide)
        self.radioButton_Sum_RQ.clicked.connect(self.pushButton_Matern.hide)
        self.radioButton_Sum_RQ.clicked.connect(self.pushButton_Poly.hide)
        self.radioButton_Sum_RQ.clicked.connect(self.pushButton_RBF.hide)
        self.radioButton_Sum_RQ.clicked.connect(self.pushButton_RQ.hide)
        self.radioButton_Sum_RQ.clicked.connect(self.pushButton_Sum_RQ.show)
        self.radioButton_Sum_RQ.clicked.connect(self.pushButton_Sum_RBF.hide)
        self.pushButton_Sum_RBF.clicked.connect(self.label_loss.show)
        self.pushButton_Sum_RQ.clicked.connect(self.label_loss.show)
        self.pushButton_4.clicked.connect(self.pushButton_2.hide)
        self.pushButton_4.clicked.connect(self.pushButton_3.hide)
        self.pushButton_regression.clicked.connect(self.pushButton.show)
        self.pushButton_regression.clicked.connect(self.pushButton_2.show)
        self.pushButton_regression.clicked.connect(self.pushButton_3.show)
        self.pushButton_4.clicked.connect(self.pushButton.hide)
        self.pushButton_regression.clicked.connect(self.pushButton_classification.hide)
        self.pushButton_4.clicked.connect(self.label.hide)
        self.pushButton_regression.clicked.connect(self.label.show)
        self.pushButton_regression.clicked.connect(self.label_6.hide)
        self.pushButton_classification.clicked.connect(self.label_6.hide)
        self.pushButton_classification.clicked.connect(self.pushButton.hide)
        self.pushButton_classification.clicked.connect(self.pushButton_2.hide)
        self.pushButton_classification.clicked.connect(self.pushButton_3.hide)
        self.pushButton_regression.clicked.connect(self.pushButton_regression.hide)
        self.pushButton_Back2.clicked.connect(self.pushButton.hide)
        self.pushButton_Back2.clicked.connect(self.pushButton_2.hide)
        self.pushButton_Back2.clicked.connect(self.pushButton_3.hide)
        self.pushButton_Back2.clicked.connect(self.pushButton_regression.show)
        self.pushButton_Back2.clicked.connect(self.pushButton_classification.show)
        self.pushButton_5.clicked.connect(self.pushButton_5.hide)
        self.pushButton_4.clicked.connect(self.pushButton_5.hide)
        self.pushButton.clicked.connect(self.pushButton_5.show)
        self.pushButton_2.clicked.connect(self.pushButton_5.show)
        self.pushButton_2.clicked.connect(self.pushButton_Back2.hide)
        self.pushButton_3.clicked.connect(self.pushButton_5.show)
        self.pushButton.clicked.connect(self.pushButton_Back2.hide)
        self.pushButton_3.clicked.connect(self.pushButton_Back2.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Back2.show)
        self.pushButton_Back2.clicked.connect(self.label.hide)
        self.pushButton_Back2.clicked.connect(self.label_6.show)
        self.pushButton_classification.clicked.connect(self.pushButton_GPC_2.show)
        self.pushButton_4.clicked.connect(self.pushButton_GPC.hide)
        self.pushButton_classification.clicked.connect(self.pushButton_regression.hide)
        self.pushButton_Back2.clicked.connect(self.pushButton_GPC.hide)
        self.pushButton_Back2.clicked.connect(self.label_5.hide)
        self.pushButton_Back2.clicked.connect(self.lineEdit.hide)
        self.pushButton_Back2.clicked.connect(self.label_predict.hide)
        self.pushButton_Back2.clicked.connect(self.label_loss.hide)
        self.pushButton_4.clicked.connect(self.pushButton_NNCL.hide)
        self.pushButton_classification.clicked.connect(self.pushButton_NNCL.show)
        self.pushButton_classification.clicked.connect(self.pushButton_classification.hide)
        self.pushButton_4.clicked.connect(self.pushButton_GPC_2.hide)
        self.pushButton_Back2.clicked.connect(self.pushButton_GPC_2.hide)
        self.pushButton_Back2.clicked.connect(self.pushButton_NNCL.hide)
        self.pushButton_GPC_2.clicked.connect(self.pushButton_GPC.show)
        self.pushButton_GPC_2.clicked.connect(self.lineEdit.show)
        self.pushButton_GPC_2.clicked.connect(self.label_5.show)
        self.pushButton_GPC_2.clicked.connect(self.label_loss.show)
        self.pushButton_GPC_2.clicked.connect(self.label_predict.show)
        self.pushButton_classification.clicked.connect(self.label.show)
        self.pushButton_GPC_2.clicked.connect(self.pushButton_NNCL.hide)
        self.pushButton_5.clicked.connect(self.label_loss.clear)
        self.pushButton_5.clicked.connect(self.pushButton_GPC.hide)
        self.pushButton_GPC_2.clicked.connect(self.pushButton_Back2.hide)
        self.pushButton_GPC_2.clicked.connect(self.pushButton_Back_3.show)
        self.pushButton_4.clicked.connect(self.pushButton_Back_3.hide)
        self.pushButton_Back_3.clicked.connect(self.pushButton_Back_3.hide)
        self.pushButton_Back_3.clicked.connect(self.lineEdit.hide)
        self.pushButton_Back_3.clicked.connect(self.pushButton_GPC.hide)
        self.pushButton_Back_3.clicked.connect(self.label_5.hide)
        self.pushButton_Back_3.clicked.connect(self.label_loss.hide)
        self.pushButton_Back_3.clicked.connect(self.label_predict.hide)
        self.pushButton_NNCL.clicked.connect(self.label_predict.show)
        self.pushButton_Back_3.clicked.connect(self.label_loss.clear)
        self.pushButton_Back_3.clicked.connect(self.label_predict.clear)
        self.pushButton_Back_3.clicked.connect(self.pushButton_Back2.show)
        self.pushButton_Back_3.clicked.connect(self.pushButton_GPC_2.show)
        self.pushButton_Back_3.clicked.connect(self.pushButton_NNCL.show)
        self.pushButton_4.clicked.connect(self.pushButton_Leaky_ReLu_cl.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Relu_cl.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Serf_cl.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Soft_Plus_cl.hide)
        self.pushButton_4.clicked.connect(self.pushButton_Swish_cl.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Leaky_ReLu_cl.hide)
        self.pushButton_4.clicked.connect(self.radioButton_ReLu_cl.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Serf_cl.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Soft_Plus_cl.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Swish_cl.hide)
        self.pushButton_NNCL.clicked.connect(self.radioButton_ReLu_cl.show)
        self.pushButton_NNCL.clicked.connect(self.radioButton_Leaky_ReLu_cl.show)
        self.pushButton_NNCL.clicked.connect(self.radioButton_Serf_cl.show)
        self.pushButton_NNCL.clicked.connect(self.radioButton_Soft_Plus_cl.show)
        self.pushButton_NNCL.clicked.connect(self.radioButton_Swish_cl.show)
        self.pushButton_NNCL.clicked.connect(self.pushButton_GPC_2.hide)
        self.pushButton_NNCL.clicked.connect(self.pushButton_Back2.hide)
        self.pushButton_NNCL.clicked.connect(self.pushButton_Back_3.show)
        self.pushButton_Back_3.clicked.connect(self.radioButton_Leaky_ReLu_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.radioButton_ReLu_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.radioButton_Serf_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.radioButton_Soft_Plus_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.radioButton_Swish_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.pushButton_Leaky_ReLu_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.pushButton_Relu_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.pushButton_Serf_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.pushButton_Soft_Plus_cl.hide)
        self.pushButton_Back_3.clicked.connect(self.pushButton_Swish_cl.hide)
        self.pushButton_NNCL.clicked.connect(self.label_2.show)
        self.pushButton_Back_3.clicked.connect(self.label_2.hide)
        self.pushButton_NNCL.clicked.connect(self.label_loss.show)
        self.pushButton_NNCL.clicked.connect(self.lineEdit.show)
        self.radioButton_Leaky_ReLu_cl.clicked.connect(self.pushButton_Leaky_ReLu_cl.show)
        self.pushButton_NNCL.clicked.connect(self.label_5.show)
        self.radioButton_Leaky_ReLu_cl.clicked.connect(self.pushButton_Serf_cl.hide)
        self.radioButton_Leaky_ReLu_cl.clicked.connect(self.pushButton_Relu_cl.hide)
        self.radioButton_Leaky_ReLu_cl.clicked.connect(self.pushButton_Soft_Plus_cl.hide)
        self.radioButton_Leaky_ReLu_cl.clicked.connect(self.pushButton_Swish_cl.hide)
        self.radioButton_ReLu_cl.clicked.connect(self.pushButton_Leaky_ReLu_cl.hide)
        self.radioButton_ReLu_cl.clicked.connect(self.pushButton_Relu_cl.show)
        self.radioButton_ReLu_cl.clicked.connect(self.pushButton_Soft_Plus_cl.hide)
        self.radioButton_ReLu_cl.clicked.connect(self.pushButton_Serf_cl.hide)
        self.radioButton_ReLu_cl.clicked.connect(self.pushButton_Swish_cl.hide)
        self.radioButton_Serf_cl.clicked.connect(self.pushButton_Leaky_ReLu_cl.hide)
        self.radioButton_Serf_cl.clicked.connect(self.pushButton_Relu_cl.hide)
        self.radioButton_Serf_cl.clicked.connect(self.pushButton_Serf_cl.show)
        self.radioButton_Serf_cl.clicked.connect(self.pushButton_Soft_Plus_cl.hide)
        self.radioButton_Serf_cl.clicked.connect(self.pushButton_Swish_cl.hide)
        self.radioButton_Soft_Plus_cl.clicked.connect(self.pushButton_Leaky_ReLu_cl.hide)
        self.radioButton_Soft_Plus_cl.clicked.connect(self.pushButton_Relu_cl.hide)
        self.radioButton_Soft_Plus_cl.clicked.connect(self.pushButton_Serf_cl.hide)
        self.radioButton_Soft_Plus_cl.clicked.connect(self.pushButton_Soft_Plus_cl.show)
        self.radioButton_Soft_Plus_cl.clicked.connect(self.pushButton_Swish_cl.hide)
        self.radioButton_Swish_cl.clicked.connect(self.pushButton_Leaky_ReLu_cl.hide)
        self.radioButton_Swish_cl.clicked.connect(self.pushButton_Relu_cl.hide)
        self.radioButton_Swish_cl.clicked.connect(self.pushButton_Serf_cl.hide)
        self.radioButton_Swish_cl.clicked.connect(self.pushButton_Soft_Plus_cl.hide)
        self.radioButton_Swish_cl.clicked.connect(self.pushButton_Swish_cl.show)
        self.pushButton_4.clicked.connect(self.pushButton_show_results.hide)
        self.pushButton_regression.clicked.connect(self.pushButton_show_results.show)
        self.pushButton_Back2.clicked.connect(self.pushButton_show_results.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_ReLu.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_Serf.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_Swish.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_Softplus.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_Three.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_Two.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_Leaky_ReLu.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_Four.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_Four.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_Leaky_ReLu.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_ReLu.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_Serf.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_Softplus.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_Swish.hide)
        self.pushButton_Back_3.clicked.connect(self.pushButton_opti_Three.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_Two.hide)
        self.pushButton_Leaky_ReLu.clicked.connect(self.pushButton_opti_Leaky_ReLu.show)
        self.pushButton_ReLu.clicked.connect(self.pushButton_opti_ReLu.show)
        self.pushButton_Softplus.clicked.connect(self.pushButton_opti_Softplus.show)
        self.pushButton_Swish.clicked.connect(self.pushButton_opti_Swish.show)
        self.pushButton_Three.clicked.connect(self.pushButton_opti_Three.show)
        self.pushButton_four.clicked.connect(self.pushButton_opti_Four.show)
        self.pushButton_two.clicked.connect(self.pushButton_opti_Two.show)
        self.pushButton_Serf.clicked.connect(self.pushButton_opti_Serf.show)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_opti_ReLu.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_Three.hide)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_opti_Serf.hide)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_opti_Softplus.hide)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_opti_Swish.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_opti_Leaky_ReLu.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_opti_Serf.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_opti_Softplus.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_opti_Swish.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_opti_Leaky_ReLu.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_opti_ReLu.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_opti_Softplus.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_opti_Swish.hide)
        self.radioButton_Sum_RBF.clicked.connect(self.pushButton_opti_Leaky_ReLu.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_opti_Leaky_ReLu.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_opti_ReLu.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_opti_Serf.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_opti_Swish.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_opti_Leaky_ReLu.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_opti_ReLu.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_opti_Serf.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_opti_Softplus.hide)
        self.radioButton_two.clicked.connect(self.pushButton_opti_Four.hide)
        self.radioButton_two.clicked.connect(self.pushButton_opti_Three.hide)
        self.radioButton_Three.clicked.connect(self.pushButton_opti_Four.hide)
        self.radioButton_Three.clicked.connect(self.pushButton_opti_Two.hide)
        self.radioButton_four.clicked.connect(self.pushButton_opti_Three.hide)
        self.radioButton_four.clicked.connect(self.pushButton_opti_Two.hide)
        self.pushButton_4.clicked.connect(self.label_num_gen.hide)
        self.pushButton_4.clicked.connect(self.label_num_indiv.hide)
        self.pushButton_4.clicked.connect(self.lineEdit_num_gen.hide)
        self.pushButton_4.clicked.connect(self.lineEdit_num_indiv.hide)
        self.pushButton_4.clicked.connect(self.label_results_opti.hide)
        self.pushButton.clicked.connect(self.label_num_gen.show)
        self.pushButton.clicked.connect(self.label_num_indiv.show)
        self.pushButton.clicked.connect(self.label_results_opti.show)
        self.pushButton.clicked.connect(self.lineEdit_num_gen.show)
        self.pushButton.clicked.connect(self.lineEdit_num_indiv.show)
        self.pushButton_5.clicked.connect(self.label_num_gen.hide)
        self.pushButton_5.clicked.connect(self.label_num_indiv.hide)
        self.pushButton_5.clicked.connect(self.label_results_opti.clear)
        self.pushButton_5.clicked.connect(self.lineEdit_num_gen.hide)
        self.pushButton_5.clicked.connect(self.lineEdit_num_indiv.hide)
        self.pushButton_2.clicked.connect(self.label_num_gen.show)
        self.pushButton_2.clicked.connect(self.label_num_indiv.show)
        self.pushButton_2.clicked.connect(self.label_results_opti.show)
        self.pushButton_2.clicked.connect(self.lineEdit_num_gen.show)
        self.pushButton_2.clicked.connect(self.lineEdit_num_indiv.show)
        self.pushButton_4.clicked.connect(self.label_7.hide)
        self.pushButton.clicked.connect(self.label_7.show)
        self.pushButton_5.clicked.connect(self.label_7.hide)
        self.pushButton_2.clicked.connect(self.label_7.show)
        self.pushButton_4.clicked.connect(self.pushButton_regression.hide)
        self.pushButton_4.clicked.connect(self.pushButton_classification.hide)
        self.pushButton_Bardenpho.clicked.connect(self.pushButton_classification.show)
        self.pushButton_Bardenpho.clicked.connect(self.pushButton_Bardenpho.hide)
        self.pushButton_Bardenpho.clicked.connect(self.pushButton_regression.show)
        self.pushButton_Bardenpho.clicked.connect(self.pushButton_A2O.hide)
        self.pushButton_Bardenpho.clicked.connect(self.pushButton_Johannesburg.hide)
        self.pushButton_Bardenpho.clicked.connect(self.pushButton_UCT.hide)
        self.pushButton_A2O.clicked.connect(self.pushButton_classification.show)
        self.pushButton_A2O.clicked.connect(self.pushButton_regression.show)
        self.pushButton_A2O.clicked.connect(self.pushButton_A2O.hide)
        self.pushButton_A2O.clicked.connect(self.pushButton_Bardenpho.hide)
        self.pushButton_A2O.clicked.connect(self.pushButton_Johannesburg.hide)
        self.pushButton_A2O.clicked.connect(self.pushButton_UCT.hide)
        self.pushBoutton_back_4.clicked.connect(self.pushButton_classification.hide)
        self.pushBoutton_back_4.clicked.connect(self.pushButton_regression.hide)
        self.pushBoutton_back_4.clicked.connect(self.pushButton_A2O.show)
        self.pushBoutton_back_4.clicked.connect(self.pushButton_Bardenpho.show)
        self.pushButton_4.clicked.connect(self.pushButton_Back2.hide)
        self.pushButton_A2O.clicked.connect(self.pushBoutton_back_4.show)
        self.pushButton_Bardenpho.clicked.connect(self.pushBoutton_back_4.show)
        self.pushButton_4.clicked.connect(self.pushBoutton_back_4.hide)
        self.pushButton_regression.clicked.connect(self.pushButton_Back2.show)
        self.pushButton_regression.clicked.connect(self.pushBoutton_back_4.hide)
        self.pushButton_Back2.clicked.connect(self.pushBoutton_back_4.show)
        self.pushButton_Back2.clicked.connect(self.pushButton_Back2.hide)
        self.pushBoutton_back_4.clicked.connect(self.pushBoutton_back_4.hide)
        self.pushButton_Johannesburg.clicked.connect(self.pushButton_A2O.hide)
        self.pushButton_Johannesburg.clicked.connect(self.pushButton_Bardenpho.hide)
        self.pushButton_Johannesburg.clicked.connect(self.pushButton_Johannesburg.hide)
        self.pushButton_Johannesburg.clicked.connect(self.pushButton_UCT.hide)
        self.pushButton_UCT.clicked.connect(self.pushButton_A2O.hide)
        self.pushButton_UCT.clicked.connect(self.pushButton_Bardenpho.hide)
        self.pushButton_UCT.clicked.connect(self.pushButton_Johannesburg.hide)
        self.pushButton_UCT.clicked.connect(self.pushButton_UCT.hide)
        self.pushButton_Johannesburg.clicked.connect(self.pushButton_classification.show)
        self.pushButton_Johannesburg.clicked.connect(self.pushButton_regression.show)
        self.pushButton_Johannesburg.clicked.connect(self.pushBoutton_back_4.show)
        self.pushButton_UCT.clicked.connect(self.pushButton_classification.show)
        self.pushButton_UCT.clicked.connect(self.pushButton_regression.show)
        self.pushButton_UCT.clicked.connect(self.pushBoutton_back_4.show)
        self.pushBoutton_back_4.clicked.connect(self.pushButton_UCT.show)
        self.pushBoutton_back_4.clicked.connect(self.pushButton_Johannesburg.show)
        self.pushButton_4.clicked.connect(self.label_6.hide)
        self.pushButton_A2O.clicked.connect(self.label_6.show)
        self.pushButton_A2O.clicked.connect(self.label_BNR.hide)
        self.pushButton_Bardenpho.clicked.connect(self.label_6.show)
        self.pushButton_Bardenpho.clicked.connect(self.label_BNR.hide)
        self.pushButton_Johannesburg.clicked.connect(self.label_6.show)
        self.pushButton_Johannesburg.clicked.connect(self.label_BNR.hide)
        self.pushButton_UCT.clicked.connect(self.label_6.show)
        self.pushButton_UCT.clicked.connect(self.label_BNR.hide)
        self.pushBoutton_back_4.clicked.connect(self.label_6.hide)
        self.pushBoutton_back_4.clicked.connect(self.label_BNR.show)
        self.pushButton_classification.clicked.connect(self.pushBoutton_back_4.hide)
        self.pushButton_classification.clicked.connect(self.pushButton_Back2.show)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_Sigmoid.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_Sigmoid.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_Sigmoid.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_Sigmoid.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_Sigmoid.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_Leaky_ReLu.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_ReLu.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_Serf.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_Softplus.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_Swish.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_Sigmoid.show)
        self.pushButton.clicked.connect(self.radioButton_Sigmoid.show)
        self.pushButton_4.clicked.connect(self.pushButton_Sigmoid.hide)
        self.pushButton_4.clicked.connect(self.radioButton_Sigmoid.hide)
        self.pushButton_5.clicked.connect(self.pushButton_Sigmoid.hide)
        self.pushButton_5.clicked.connect(self.radioButton_Sigmoid.hide)
        self.pushButton_5.clicked.connect(self.pushButton_opti_Sigmoid.hide)
        self.pushButton_4.clicked.connect(self.pushButton_opti_Sigmoid.hide)
        self.radioButton_Leaky_ReLu.clicked.connect(self.pushButton_opti_Sigmoid.hide)
        self.radioButton_ReLu.clicked.connect(self.pushButton_opti_Sigmoid.hide)
        self.radioButton_Serf.clicked.connect(self.pushButton_opti_Sigmoid.hide)
        self.radioButton_SoftPlus.clicked.connect(self.pushButton_opti_Sigmoid.hide)
        self.radioButton_Swish.clicked.connect(self.pushButton_opti_Sigmoid.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_opti_Leaky_ReLu.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_opti_ReLu.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_opti_Serf.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_opti_Softplus.hide)
        self.radioButton_Sigmoid.clicked.connect(self.pushButton_opti_Swish.hide)
        self.pushButton_Sigmoid.clicked.connect(self.label_loss.show)
        self.pushButton_Sigmoid.clicked.connect(self.pushButton_opti_Sigmoid.show)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GUI", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Gaussian Process (Regression)", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Deep Gaussian Process", None))
        self.pushButton_classification.setText(QCoreApplication.translate("MainWindow", u"Classification", None))
        self.pushButton_regression.setText(QCoreApplication.translate("MainWindow", u"Regression ", None))
        self.pushButton_A2O.setText(QCoreApplication.translate("MainWindow", u"A2O", None))
        self.pushButton_Bardenpho.setText(QCoreApplication.translate("MainWindow", u"Bardenpho", None))
        self.pushButton_Johannesburg.setText(QCoreApplication.translate("MainWindow", u"Johannesburg", None))
        self.pushButton_UCT.setText(QCoreApplication.translate("MainWindow", u"UCT", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Neural Network (Regression)", None))
        self.pushButton_NNCL.setText(QCoreApplication.translate("MainWindow", u"Neural Network (Classification)", None))
        self.pushButton_GPC_2.setText(QCoreApplication.translate("MainWindow", u"Gaussian process (Classification)", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"click here to start", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Please Select an activation function ", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Please select a kernel Function", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Please select the number of layers ", None))
        self.pushBoutton_back_4.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.pushButton_Back2.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.pushButton_Back_3.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.radioButton_four.setText(QCoreApplication.translate("MainWindow", u"Four ", None))
        self.radioButton_Poly.setText(QCoreApplication.translate("MainWindow", u"Polynomial", None))
        self.radioButton_SoftPlus.setText(QCoreApplication.translate("MainWindow", u"SoftPlus", None))
        self.radioButton_RBF.setText(QCoreApplication.translate("MainWindow", u"RBF", None))
        self.radioButton_ESS.setText(QCoreApplication.translate("MainWindow", u"ESS", None))
        self.radioButton_Linear.setText(QCoreApplication.translate("MainWindow", u"Linear", None))
        self.radioButton_Matern.setText(QCoreApplication.translate("MainWindow", u"Matern", None))
        self.radioButton_Three.setText(QCoreApplication.translate("MainWindow", u"Three", None))
        self.radioButton_Leaky_ReLu.setText(QCoreApplication.translate("MainWindow", u"Leaky ReLu", None))
        self.radioButton_Swish.setText(QCoreApplication.translate("MainWindow", u"Swish", None))
        self.radioButton_ReLu.setText(QCoreApplication.translate("MainWindow", u"ReLu", None))
        self.radioButton_two.setText(QCoreApplication.translate("MainWindow", u"Two", None))
        self.radioButton_RQ.setText(QCoreApplication.translate("MainWindow", u"Rational Quadratic", None))
        self.radioButton_Serf.setText(QCoreApplication.translate("MainWindow", u"Serf", None))
        self.pushButton_Serf.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_RQ.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_two.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_ReLu.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Swish.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Leaky_ReLu.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Three.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Matern.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Linear.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_ESS.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_RBF.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Softplus.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Poly.setText(QCoreApplication.translate("MainWindow", u"fit and predict ", None))
        self.pushButton_four.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.label_loss.setText("")
        self.radioButton_Sum_RBF.setText(QCoreApplication.translate("MainWindow", u"Sum RBF", None))
        self.pushButton_Sum_RBF.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.radioButton_Sum_RQ.setText(QCoreApplication.translate("MainWindow", u"Sum RQ", None))
        self.pushButton_Sum_RQ.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_GPC.setText(QCoreApplication.translate("MainWindow", u"fit and predict ", None))
        self.radioButton_Serf_cl.setText(QCoreApplication.translate("MainWindow", u"Serf", None))
        self.radioButton_Swish_cl.setText(QCoreApplication.translate("MainWindow", u"Swish", None))
        self.radioButton_ReLu_cl.setText(QCoreApplication.translate("MainWindow", u"ReLu", None))
        self.radioButton_Leaky_ReLu_cl.setText(QCoreApplication.translate("MainWindow", u"Leaky ReLu", None))
        self.pushButton_Serf_cl.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Swish_cl.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Relu_cl.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.pushButton_Leaky_ReLu_cl.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.radioButton_Soft_Plus_cl.setText(QCoreApplication.translate("MainWindow", u"Soft Plus", None))
        self.pushButton_Soft_Plus_cl.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.radioButton_Sigmoid.setText(QCoreApplication.translate("MainWindow", u"Sigmoid", None))
        self.pushButton_Sigmoid.setText(QCoreApplication.translate("MainWindow", u"fit and predict", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"please enter your input value for prediction below ", None))
        self.label_predict.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Please Click on a machine learning algorithm ", None))
        self.label_BNR.setText(QCoreApplication.translate("MainWindow", u"Please Select a BNR process ", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"please select an application ", None))
        self.pushButton_show_results.setText(QCoreApplication.translate("MainWindow", u"Results ", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"please enter the parameters for optimisation ", None))
        self.label_num_indiv.setText(QCoreApplication.translate("MainWindow", u"number of individuals (population size)", None))
        self.label_num_gen.setText(QCoreApplication.translate("MainWindow", u"number of generations ", None))
        self.pushButton_opti_Sigmoid.setText(QCoreApplication.translate("MainWindow", u"Run optimisation", None))
        self.pushButton_opti_Two.setText(QCoreApplication.translate("MainWindow", u"Run optimisation", None))
        self.pushButton_opti_ReLu.setText(QCoreApplication.translate("MainWindow", u"Run optimisation", None))
        self.pushButton_opti_Swish.setText(QCoreApplication.translate("MainWindow", u"Run optimisation ", None))
        self.pushButton_opti_Leaky_ReLu.setText(QCoreApplication.translate("MainWindow", u"Run optimisation", None))
        self.pushButton_opti_Softplus.setText(QCoreApplication.translate("MainWindow", u"Run optimisation ", None))
        self.pushButton_opti_Four.setText(QCoreApplication.translate("MainWindow", u"Run optimisation", None))
        self.pushButton_opti_Three.setText(QCoreApplication.translate("MainWindow", u"Run optimisation", None))
        self.pushButton_opti_Serf.setText(QCoreApplication.translate("MainWindow", u"Run optimisation", None))
        self.label_results_opti.setText("")
    # retranslateUi

